### ISSUE TITLE
Feedback Tugas 9 Basis Data

### ISSUE THREAD

**Issue by NelanJoe** [sh1z1a/tugas2_basisdata#1]
Hallo @sh1z1a terimakasih ya udah ngumpulin dan berusahan untuk ngerjain dengan sebaiknya,.
Sedikit catatan dari aku:
- Mungkin untuk kedepannya jangan sampai telat mengumpulkan tugasnya, karena konsekuensinya bisa lebih fatal untuk nilainya.
- Untuk sqlnya aku ndak tau yang mana yang mau aku koreksi baik - baik, soalnya ada _2 file sql_ 
- Untuk ERD nya sudah bagus ya,.

Oke @sh1z1a  tetap semangat ya 💪

**Comment by sh1z1a** [comment]
Hallo juga bang @NelanJoe , Terimakasih atas feedback nya. Insya Allah kedepannya saya lebih on time lagi. untuk sql saya tidak pakai file txt melainkan sql jadi otomatis terpisah, tetapi saya punya file txt nya untuk itu saya kirimkan file txt nya di folder ini.
